image: registry.gitlab.com/panw-gse/as/as-py-base-image:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv .venv
  - source .venv/bin/activate

test:
  script:
    - pip install --upgrade sli
    - sli load -le

