# snippets is used to load a full NGFW configuration

# snippet folder name
name: k_12_config_skillet
# label used for menu selection
label: Configuration Skillet for K-12 Solution
description: K-12 Safe Search Skillet baseline configuration for a firewall

type: panos

# grouping of like snippets for dynamic menu creation in pan-cnc
labels:
  service_type: K12_skillet
  collection:
    - Education

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: TRUST_ZONE_INTERFACE
    description: Trusted Interface reference
    default: ethernet1/2
    type_hint: text

  - name: TRUSTED_INTERFACE_IP
    description: Trusted Interface IP
    default: 192.0.2.100/32
    type_hint: text

  - name: UNTRUST_ZONE_INTERFACE
    description: Untrusted Interface reference
    default: ethernet1/1
    type_hint: text

  - name: SNIPPET_EXECUTION
    description: Pick Snippets to Load
    default: ['safe_search']
    type_hint: checkbox
    cbx_list:
      - key: Configure Safe Search Enforcement
        value: safe_search
      - key: Permit traffic only from US, Mexico, Canada, and Cloud Providers EDL
        value: country_block
      - key: Configure Chromebook Bypass with No Decrypt Policy
        value: chromebook_bypass
      - key: Configure SAML No Decrypt Policy
        value: saml_no_decryption

  # this configuration allows you to select what type of Safe Search configuration
  # to be used during the configuration build
  - name: SAFE_SEARCH
    description: What type of Safe Search configuration do you want to enable?
    default: 'None'
    type_hint: dropdown
    toggle_hint:
      source: SNIPPET_EXECUTION
      value: safe_search
    dd_list:
      - key: 'None'
        value: 'NONE'
      - key: 'SSL Decryption'
        value: 'SSL_DECRYPTION'
      - key: 'DNS Proxy'
        value: 'DNS_PROXY'
      - key: 'Local DNS CNAME'
        value: 'LOCAL_DNS_CNAME'

# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
    # Used in DNS Proxy as Destination
  - name: address
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/address
    element: |
      <entry name="FW - Trust">
        <ip-netmask>{{ TRUSTED_INTERFACE_IP.split('/')[0] }}/32</ip-netmask>
      </entry>

  - name: interface
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/interface
    element: |
      <ethernet>
        <entry name="ethernet1/1">
          <layer3>
            <ipv6>
              <neighbor-discovery>
                <router-advertisement>
                  <enable>no</enable>
                </router-advertisement>
              </neighbor-discovery>
            </ipv6>
            <ndp-proxy>
              <enabled>no</enabled>
            </ndp-proxy>
            <lldp>
              <enable>no</enable>
            </lldp>
            <dhcp-client/>
          </layer3>
        </entry>
        <entry name="ethernet1/2">
          <layer3>
            <ipv6>
              <neighbor-discovery>
                <router-advertisement>
                  <enable>no</enable>
                </router-advertisement>
              </neighbor-discovery>
            </ipv6>
            <ndp-proxy>
              <enabled>no</enabled>
            </ndp-proxy>
            <lldp>
              <enable>no</enable>
            </lldp>
            <ip>
              <entry name="{{ TRUSTED_INTERFACE_IP }}{{ TRUSTED_INTERFACE_SUBNET }}"/>
            </ip>
          </layer3>
        </entry>
      </ethernet>

  - name: virtual_router
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/virtual-router
    element: |
      <entry name="default">
        <protocol>
          <bgp>
            <enable>no</enable>
            <dampening-profile>
              <entry name="default">
                <cutoff>1.25</cutoff>
                <reuse>0.5</reuse>
                <max-hold-time>900</max-hold-time>
                <decay-half-life-reachable>300</decay-half-life-reachable>
                <decay-half-life-unreachable>900</decay-half-life-unreachable>
                <enable>yes</enable>
              </entry>
            </dampening-profile>
          </bgp>
        </protocol>
        <interface>
          <member>ethernet1/1</member>
          <member>ethernet1/2</member>
        </interface>
      </entry>

  - name: zone
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone
    element: |
      <entry name="Untrust">
        <network>
          <layer3>
            <member>{{ UNTRUST_ZONE_INTERFACE }}</member>
          </layer3>
        </network>
      </entry>
      <entry name="Trust">
        <network>
          <layer3>
            <member>{{ TRUST_ZONE_INTERFACE }}</member>
          </layer3>
        </network>
      </entry>

  - name: panos_k12_base_common_elements_10_0
    include: panos_k12_base_common_elements_10_0

  - name: panos_k12_country_block_10_0
    include: panos_k12_country_block_10_0
    include_variables:
      - name: all
        toggle_hint:
          source: SNIPPET_EXECUTION
          value: 'country_block'
    when: "'country_block' in SNIPPET_EXECUTION"

  - name: panos_k12_ssl_decryption_10_0
    include: panos_k12_ssl_decryption_10_0
    include_variables:
      - name: all
        toggle_hint:
          source: SAFE_SEARCH
          value: 'SSL_DECRYPTION'
    when: "'safe_search' in SNIPPET_EXECUTION and 'SSL_DECRYPTION' in SAFE_SEARCH"

  - name: panos_k12_dns_proxy_10_0
    include: panos_k12_dns_proxy_10_0
    include_variables:
      - name: all
        toggle_hint:
          source: SAFE_SEARCH
          value: 'DNS_PROXY'
    when: "'safe_search' in SNIPPET_EXECUTION and 'DNS_PROXY' in SAFE_SEARCH"

  - name: panos_k12_local_dns_cname_10_0
    include: panos_k12_local_dns_cname_10_0
    include_variables:
      - name: all
        toggle_hint:
          source: SAFE_SEARCH
          value: 'LOCAL_DNS_CNAME'
    when: "'safe_search' in SNIPPET_EXECUTION and 'LOCAL_DNS_CNAME' in SAFE_SEARCH"

  - name: panos_k12_chromebook_no_decryption_10_0
    include: panos_k12_chromebook_no_decryption_10_0
    when: "'chromebook_bypass' in SNIPPET_EXECUTION"

  - name: panos_k12_saml_no_decryption_10_0
    include: panos_k12_saml_no_decryption_10_0
    when: "'saml_no_decryption' in SNIPPET_EXECUTION"